# Generated by Django 5.0.8 on 2024-08-20 17:21

import django.core.validators
from django.db import migrations, models

import core.services.file_service


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0008_alter_carmodel_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carmodel',
            name='brand',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator('^[A-Z][\\S]{1,19}$', 'First letter uppercase min 2, max 20')]),
        ),
        migrations.AlterField(
            model_name='carmodel',
            name='photo',
            field=models.ImageField(blank=True, upload_to=core.services.file_service.FileService.upload_car_photo, validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg'])]),
        ),
    ]
