# Generated by Django 5.0.8 on 2024-08-23 20:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0009_alter_carmodel_brand_alter_carmodel_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carmodel',
            name='auto_park',
        ),
        migrations.RemoveField(
            model_name='carmodel',
            name='photo',
        ),
    ]
