# Generated by Django 5.0.8 on 2024-08-20 17:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto_parks', '0002_alter_autoparkmodel_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='autoparkmodel',
            options={'ordering': ['id']},
        ),
        migrations.AlterField(
            model_name='autoparkmodel',
            name='name',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator('^[A-Z][\\S]{0,19}$', 'First letter uppercase min 1, max 20')]),
        ),
    ]
